### ISSUE TITLE
Fix some typos

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kward/shflags#25]
```
Just some minor typo fixes, in comments and output.
```

Original issue reported on code.google.com by `pvanderdoes@gmail.com` on 18 Jan 2013 at 4:24

Attachments:
- [typos.diff](https://storage.googleapis.com/google-code-attachments/shflags/issue-25/comment-0/typos.diff)

**Comment by petervanderdoes** [comment]
See Pull Request #35

**Comment by kward** [comment]
Thanks for the patch!
