### ISSUE TITLE
Code review request: Refactor function _flags_itemInList

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kward/shflags#26]
```
Purpose of code changes:
Remove the use of an external command to determine if an item is in a list.

When reviewing my code changes, please focus on:
The function _flags_itemInList



```

Original issue reported on code.google.com by `pvanderdoes@gmail.com` on 24 Jan 2013 at 6:11

Attachments:
- [refactor_itemInList.diff](https://storage.googleapis.com/google-code-attachments/shflags/issue-26/comment-0/refactor_itemInList.diff)

**Comment by petervanderdoes** [comment]
See Pull Request #33

**Comment by kward** [comment]
Committed. Thank you for the pull request!
