### ISSUE TITLE
Code review request: Fixes for the test testItemInList() in shflags_test_private.sh

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kward/shflags#27]
```
Purpose of code changesL
Several tests were wrong. The wrong item was checked.
Added three additional tests.
```

Original issue reported on code.google.com by `pvanderdoes@gmail.com` on 24 Jan 2013 at 6:14

Attachments:
- [privet_test_fixes.diff](https://storage.googleapis.com/google-code-attachments/shflags/issue-27/comment-0/privet_test_fixes.diff)

**Comment by petervanderdoes** [comment]
See Pull Request #33

**Comment by kward** [comment]
Committed. Thank you for the pull request!
