### ISSUE TITLE
Do not export FLAGS_ARGC

### ISSUE THREAD

**Issue by sergey-s-betke** [kward/shflags#50]
There is error if current script and subscript (even is subshell) used shflags.

https://ci.appveyor.com/project/sergey-s-betke/marks/build/2.3.0.317

> ../ITG.MakeUtils/shflags/shflags: line 759: FLAGS_ARGC: readonly variable

**Comment by mtsgrd** [comment]
Confirmed!

**Comment by yjlou** [comment]
I have this issue too. I cannot call another script using shflags too.

**Comment by ddidier** [comment]
I just wrote two long scripts to only find that I couldn't call it from one another.
Is there any workaround? It looks like just commenting out the export does the job but...

**Comment by yjlou** [comment]
Thanks for fixing this. Will try it out. ^_^

**Comment by brzyangg** [comment]
what is the cause of this problem?
